"use client";
import React from "react";
import { Container } from "@/components/Container";
import { Disclosure, DisclosureButton, DisclosurePanel } from "@headlessui/react";
import { ChevronUpIcon } from "@heroicons/react/24/solid";

export const Faq = () => {
  return (
    <Container className="!p-0">
      <div className="w-full max-w-2xl p-2 mx-auto rounded-2xl">
        {faqdata.map((item, index) => (
          <div key={item.question} className="mb-5">
            <Disclosure>
              {({ open }) => (
                <>
                  <DisclosureButton className="flex items-center justify-between w-full px-4 py-4 text-lg text-left text-gray-800 rounded-lg bg-gray-50 hover:bg-gray-100 focus:outline-none focus-visible:ring focus-visible:ring-indigo-100 focus-visible:ring-opacity-75 dark:bg-trueGray-800 dark:text-gray-200">
                    <span>{item.question}</span>
                    <ChevronUpIcon
                      className={`${
                        open ? "transform rotate-180" : ""
                      } w-5 h-5 text-indigo-500`}
                    />
                  </DisclosureButton>
                  <DisclosurePanel className="px-4 pt-4 pb-2 text-gray-500 dark:text-gray-300">
                    {item.answer}
                  </DisclosurePanel>
                </>
              )}
            </Disclosure>
          </div>
        ))}
      </div>
    </Container>
  );
}

const faqdata = [
  {
    question: "What is PostCraft AI?",
    answer: "PostCraft AI is an advanced AI-powered platform that helps you generate engaging social media content in just a few clicks. Whether you need captions, blog posts, or even ads, PostCraft AI provides ready-to-use content tailored to your brand.",
  },
  {
    question: "How does PostCraft AI generate content?",
    answer: "Our platform uses cutting-edge AI algorithms to analyze trends, language patterns, and the specific tone you choose. It crafts unique, high-quality content that resonates with your audience and boosts your engagement.",
  },
  {
    question: "Can I customize the content generated by PostCraft AI?",
    answer:
      "Absolutely! PostCraft AI allows you to fully customize the generated content. You can adjust the tone, length, and specific keywords to fit your brand's voice.",
  },
  {
    question: "What social media platforms are supported?",
    answer:
      "PostCraft AI generates content for platforms like Instagram, Facebook, Twitter, LinkedIn, and more. We continuously add new features and platform support to meet your content needs.",
  },
  {
    question: "Is PostCraft AI free to use?",
    answer:
      "We offer a free version with basic features to get you started. You can upgrade to premium plans for access to advanced content generation tools and customization options.",
  },
  {
    question: "Can I generate content for ads and blogs?",
    answer:
      "Yes! PostCraft AI is versatile and can generate content for blogs, social media ads, product descriptions, and more, all customized to your needs.",
  },
];
